#!/usr/bin/env bash
set -e

LIBDIR="/usr/lib/xor/"

source "$LIBDIR/lib/config.sh"
source "$LIBDIR/lib/messages.sh"
source "$LIBDIR/lib/commands.sh"

source "$LIBDIR/src/installer.sh"
source "$LIBDIR/src/remover.sh"
source "$LIBDIR/src/templater"
source "$LIBDIR/src/sync"

source "$LIBDIR/db/listing.sh"

INTERACTIVE_MODE=false
VERBOSE_MODE=false
DEBUG_MODE=false


show_help() {

cat <<- EOF
    Usage: xor <command> [options] <package>

    Avaible commands:
      install		Install package
      remove		Remove package
      reinstall		Remove and install package
      sync		Sync ports
      list		List installed packages
      list-repository	List avaible packages to install
      depends		List package dependecies
      templater		Create a package template

EOF
    exit 0
 #    Options:
	# -i, --interactive   Perguntar para cada dependência antes de instalar
	# -v, --verbose       Mostrar mais detalhes durante a execução
	# -h, --help          Mostrar esta ajuda
}

ensure_package_specified() {
    if [ -z "$PKG_NAME" ]; then
	msgerr "Error: No package specified."
	exit 1
    fi
}

reinstall_package() {
    remove_package "$1" &&
    check_already_installed "$1"
}

COMMAND=""
PKG_NAME=""


need_root() {

    # Root detection TODO: NEED TO CHANGE
    if [[ $(whoami) == "root" ]]; then
	return
    fi
    msgerr "This command needs root"
    interrupt
}


while [[ $# -gt 0 ]]; do
    case "$1" in
	install|remove|reinstall|depends|list|list-repository|templater|sync)
	    COMMAND="$1"
	    shift
	    if [[ $# -gt 0 ]]; then
		PKG_NAME=$(echo "$1" | tr '[:upper:]' '[:lower:]')
		shift
	    fi
	    ;;
	-i|--interactive)
	    INTERACTIVE_MODE=true
	    shift
	    ;;
	-v|--verbose)
	    VERBOSE_MODE=true
	    shift
	    ;;
	    -h|--help)
		show_help
		;;
	    *)
		msgerr "Error: Unknow command or option '$1'"
		show_help
		;;
	esac
done

case "$COMMAND" in
    install)
	need_root
        ensure_package_specified
	check_already_installed "$PKG_NAME"
        ;;
    remove)
	need_root
        ensure_package_specified
        remove_package "$PKG_NAME"
        ;;
    reinstall)
	need_root
	ensure_package_specified
	reinstall_package "$PKG_NAME"
	;;
    sync)
	need_root
	sync_ports
	;;
    list)
        list_installed_packages "$PKG_NAME"
        ;;
    list-repository)
        list_repository "$PKG_NAME"
        ;;
    depends)
	show_dependencies "$PKG_NAME"
	;;
    templater)
	need_root
        ensure_package_specified
	create_template "$PKG_NAME"
	;;
    *)
        # msgerr "Erro: Nenhum comando válido foi especificado."
        show_help
        ;;
esac
