#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh
source $(dirname "$0")/../core/messages.sh

search_repositories() {
	PKG=$1

	if [ -n "$1" ]; then
		result=$(find "$MANAGER_REPOSITORY/" -mindepth 2 -maxdepth 2 -type d -iname "$1" -exec basename {} \; | grep -v "^repository$")
	else
		result=$(find "$MANAGER_REPOSITORY" -mindepth 2 -maxdepth 2 -type d -exec basename {} \; | grep -v "^repository$")
	fi
	echo "$result"
}
