#!/usr/bin/env bash
set -e

LIBDIR="/usr/lib/xor"

source "$LIBDIR/lib/config.sh"
source "$LIBDIR/lib/messages.sh"

search_repositories() {
	local pkg=$1

	if [ -n "$pkg" ]; then
		result=$(find "$MANAGER_REPOSITORY/" -mindepth 2 -maxdepth 2 -type d -iname "$pkg" -not -path "*/.*" -exec basename {} \; | grep -v "^repository$")
	else
		result=$(find "$MANAGER_REPOSITORY" -mindepth 2 -maxdepth 2 -type d -not -path "*/.*" -exec basename {} \; | grep -v "^repository$")
	fi
	echo "$result"
}

find_pkg_repository() {
	local pkg=$1

	if [ ! -n "$pkg" ]; then
		return 1
	fi

	result=$(find "$MANAGER_REPOSITORY/" -mindepth 2 -maxdepth 2 -type d -iname "$pkg" | grep -v "^repository$")
	result="$(dirname "$result")"
	echo "$(basename "$result")"
}
