#!/usr/bin/env bash
set -e

LIBDIR="/usr/lib/xor"

source "$LIBDIR/lib/config.sh"
source "$LIBDIR/lib/messages.sh"

create_template() {

PACKAGE_NAME=$(echo "$1" | tr '[:upper:]' '[:lower:]')
msg3 "Package name: $PACKAGE_NAME"
echo ""

if [ -z "$PACKAGE_NAME" ]; then
	echo "Put the package name"
	exit 1
fi

PACKAGE_DIRECTORY=$MANAGER_REPOSITORY/$PACKAGE_NAME


if [ -d "$PACKAGE_DIRECTORY" ]; then
	echo "The repository package already exist"
	exit 1
fi

mkdir -p $MANAGER_REPOSITORY/$PACKAGE_NAME
echo "Created: $PACKAGE_DIRECTORY"

msg3 "Write the pkg version"
read -r pkg_ver
pkg_ver=${pkg_ver:-""}

echo ""

msg3 "Write the pkg url"
read -r pkg_url
pkg_url=${pkg_url:-""}


#TODO: Add read for each and probably a pushd

tee "$PACKAGE_DIRECTORY/XORBUILD" > /dev/null << EOF
#!/usr/bin/env bash
set -e

name=$PACKAGE_NAME
ver=$pkg_ver
dependencies=()

make_dependencies=""
url=$pkg_url

configure() {
}

build() {
}

EOF

chmod +x "$PACKAGE_DIRECTORY/XORBUILD"

echo "Package template for $PACKAGE_NAME was created successfully!"

}
